num_1 = int(input("Введите первую цифру "))
num_2 = int(input("Введите вторую цифру "))
string_1 = input("Введите первую строку ")
string_2 = input("Введите вторую строку ")
print(num_1, num_2, string_1, string_2)
